CI: Change check-if-version-bumped

diff --git a/.github/workflows/check-version-bump.yml b/.github/workflows/check-version-bump.yml
--- a/.github/workflows/check-version-bump.yml
+++ b/.github/workflows/check-version-bump.yml
@@ -16,7 +16,21 @@ jobs:
     name: Check version bump
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v5
       - name: Check if version bumped
-        uses: del-systems/check-if-version-bumped@v2
-
+        id: version-check
+        continue-on-error: ${{startsWith(github.head_ref, 'dependabot/')}}
+        run: |
+          npm install --no-save semver
+          PREVIOUS_COMMIT="${{github.event.pull_request.base.sha || github.event.before}}"
+          git fetch origin "$PREVIOUS_COMMIT"
+          echo Comparing version bump against "$PREVIOUS_COMMIT"
+          DEFAULT_BRANCH_VERSION="$(git show "$PREVIOUS_COMMIT:package.json" | jq -r .version)"
+          CURRENT_BRANCH_VERSION="$(git show "HEAD:package.json" | jq -r .version)"
+          if npx semver -r "$CURRENT_BRANCH_VERSION" "$DEFAULT_BRANCH_VERSION"; then
+            echo "Error: No version bump detected (prev $DEFAULT_BRANCH_VERSION" current "$CURRENT_BRANCH_VERSION)."
+            exit 1
+          else
+            echo Version bump detected: "$DEFAULT_BRANCH_VERSION -> $CURRENT_BRANCH_VERSION"
+          fi
